version: "3.8"

services:
  # Database Service
  db:
    image: postgres:15-alpine
    container_name: my_monorepo_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgresAldin
      POSTGRES_PASSWORD: aldinIzCarobneLampe
      POSTGRES_DB: postgresDB
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgresAldin -d postgresDB"]
      interval: 5s
      timeout: 5s
      retries: 5

  # PGAdmin (Web UI to view your DB)- http://localhost:5050
  pgadmin:
    image: dpage/pgadmin4
    container_name: my_monorepo_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data:
