services:
  app:
    build: .
    container_name: fastapi-dev
    ports:
      - "8000:8000"
    command: uv run uvicorn main:app
    environment:
      DATABASE_URL: postgresql://user:password@db:5435/testdb
      DATABASE_HOST: db
      DATABASE_PORT: 5435
        - WATCHFILES_FORCE_POLLING=true
    restart: always


  db:
    image: postgres:15-alpine
    container_name: postgres_test
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testdb

    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5435
    ports:
      - "5435:5435"
    command: postgres -p 5435

volumes:
  postgres_data: